// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void top_Animation(lv_obj_t * TargetObject, int delay);
void tisk_Animation(lv_obj_t * TargetObject, int delay);
void nor_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Spinner1;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Spinner3;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_1556206860);    // assets/money-currency-converter-fill.png
LV_IMG_DECLARE(ui_img_2080870776);    // assets/settings-fill.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
