// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern void ui_event_Screen3(lv_event_t * e);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label55;
extern lv_obj_t * ui_Label56;
extern lv_obj_t * ui_Label57;
extern lv_obj_t * ui_Label58;
extern lv_obj_t * ui_Label59;
extern lv_obj_t * ui_Label60;
extern lv_obj_t * ui_Label61;
extern lv_obj_t * ui_Bar4;
extern lv_obj_t * ui_Bar5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

