// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_S1MHZ3;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_S1MHZ2;
extern lv_obj_t * ui_S1MHZ1;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_Bar3;
extern lv_obj_t * ui_S1KHZ3;
extern lv_obj_t * ui_S1KHZ2;
extern lv_obj_t * ui_S1KHZ1;
extern lv_obj_t * ui_Label74;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Image10;
// CUSTOM VARIABLES
extern lv_obj_t * uic_SI_MHZ_3;
extern lv_obj_t * uic_Label2;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

