// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_SCREEN4_H
#define UI_SCREEN4_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen4
extern void ui_Screen4_screen_init(void);
extern void ui_Screen4_screen_destroy(void);
extern void ui_event_Screen4(lv_event_t * e);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Label62;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Label63;
extern lv_obj_t * ui_Label64;
extern lv_obj_t * ui_Label65;
extern lv_obj_t * ui_Label66;
extern lv_obj_t * ui_Label67;
extern lv_obj_t * ui_Label68;
extern lv_obj_t * ui_Label69;
extern lv_obj_t * ui_Bar6;
extern lv_obj_t * ui_Bar7;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

