// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen2.h"
#include "screens/ui_Screen1.h"
#include "screens/ui_Screen3.h"
#include "screens/ui_Screen4.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * removedown1_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * removedown11_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_main_png);    // assets/main.png
LV_IMG_DECLARE(ui_img_lock_png);    // assets/lock.png

// FONTS
LV_FONT_DECLARE(ui_font_AlimamaDaoLiTi16);
LV_FONT_DECLARE(ui_font_AlimamaDaoLiTi32);
LV_FONT_DECLARE(ui_font_YeZiGongChangXiaoShiTou18);
LV_FONT_DECLARE(ui_font_YeZiGongChangXiaoShiTou32);
LV_FONT_DECLARE(ui_font_YeZiGongChangXiaoShiTou64);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
